INSERT INTO city (id, name, departmentId) VALUES (5001, 'Medellín', 5);
INSERT INTO city (id, name, departmentId) VALUES (5002, 'Abejorral', 5);
INSERT INTO city (id, name, departmentId) VALUES (5004, 'Abriaquí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5021, 'Alejandría', 5);
INSERT INTO city (id, name, departmentId) VALUES (5030, 'Amagá', 5);
INSERT INTO city (id, name, departmentId) VALUES (5031, 'Amalfi', 5);
INSERT INTO city (id, name, departmentId) VALUES (5034, 'Andes', 5);
INSERT INTO city (id, name, departmentId) VALUES (5036, 'Angelópolis', 5);
INSERT INTO city (id, name, departmentId) VALUES (5038, 'Angostura', 5);
INSERT INTO city (id, name, departmentId) VALUES (5040, 'Anorí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5042, 'Santafé de Antioquia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5044, 'Anza', 5);
INSERT INTO city (id, name, departmentId) VALUES (5045, 'Apartadó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5051, 'Arboletes', 5);
INSERT INTO city (id, name, departmentId) VALUES (5055, 'Argelia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5059, 'Armenia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5079, 'Barbosa', 5);
INSERT INTO city (id, name, departmentId) VALUES (5086, 'Belmira', 5);
INSERT INTO city (id, name, departmentId) VALUES (5088, 'Bello', 5);
INSERT INTO city (id, name, departmentId) VALUES (5091, 'Betania', 5);
INSERT INTO city (id, name, departmentId) VALUES (5093, 'Betulia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5101, 'Ciudad Bolívar', 5);
INSERT INTO city (id, name, departmentId) VALUES (5107, 'Briceño', 5);
INSERT INTO city (id, name, departmentId) VALUES (5113, 'Buriticá', 5);
INSERT INTO city (id, name, departmentId) VALUES (5120, 'Cáceres', 5);
INSERT INTO city (id, name, departmentId) VALUES (5125, 'Caicedo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5129, 'Caldas', 5);
INSERT INTO city (id, name, departmentId) VALUES (5134, 'Campamento', 5);
INSERT INTO city (id, name, departmentId) VALUES (5138, 'Cañasgordas', 5);
INSERT INTO city (id, name, departmentId) VALUES (5142, 'Caracolí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5145, 'Caramanta', 5);
INSERT INTO city (id, name, departmentId) VALUES (5147, 'Carepa', 5);
INSERT INTO city (id, name, departmentId) VALUES (5148, 'El Carmen de Viboral', 5);
INSERT INTO city (id, name, departmentId) VALUES (5150, 'Carolina', 5);
INSERT INTO city (id, name, departmentId) VALUES (5154, 'Caucasia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5172, 'Chigorodó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5190, 'Cisneros', 5);
INSERT INTO city (id, name, departmentId) VALUES (5197, 'Cocorná', 5);
INSERT INTO city (id, name, departmentId) VALUES (5206, 'Concepción', 5);
INSERT INTO city (id, name, departmentId) VALUES (5209, 'Concordia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5212, 'Copacabana', 5);
INSERT INTO city (id, name, departmentId) VALUES (5234, 'Dabeiba', 5);
INSERT INTO city (id, name, departmentId) VALUES (5237, 'Don Matías', 5);
INSERT INTO city (id, name, departmentId) VALUES (5240, 'Ebéjico', 5);
INSERT INTO city (id, name, departmentId) VALUES (5250, 'El Bagre', 5);
INSERT INTO city (id, name, departmentId) VALUES (5264, 'Entrerrios', 5);
INSERT INTO city (id, name, departmentId) VALUES (5266, 'Envigado', 5);
INSERT INTO city (id, name, departmentId) VALUES (5282, 'Fredonia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5284, 'Frontino', 5);
INSERT INTO city (id, name, departmentId) VALUES (5306, 'Giraldo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5308, 'Girardota', 5);
INSERT INTO city (id, name, departmentId) VALUES (5310, 'Gómez Plata', 5);
INSERT INTO city (id, name, departmentId) VALUES (5313, 'Granada', 5);
INSERT INTO city (id, name, departmentId) VALUES (5315, 'Guadalupe', 5);
INSERT INTO city (id, name, departmentId) VALUES (5318, 'Guarne', 5);
INSERT INTO city (id, name, departmentId) VALUES (5321, 'Guatapé', 5);
INSERT INTO city (id, name, departmentId) VALUES (5347, 'Heliconia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5353, 'Hispania', 5);
INSERT INTO city (id, name, departmentId) VALUES (5360, 'Itagui', 5);
INSERT INTO city (id, name, departmentId) VALUES (5361, 'Ituango', 5);
INSERT INTO city (id, name, departmentId) VALUES (5364, 'Jardín', 5);
INSERT INTO city (id, name, departmentId) VALUES (5368, 'Jericó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5376, 'La Ceja', 5);
INSERT INTO city (id, name, departmentId) VALUES (5380, 'La Estrella', 5);
INSERT INTO city (id, name, departmentId) VALUES (5390, 'La Pintada', 5);
INSERT INTO city (id, name, departmentId) VALUES (5400, 'La Unión', 5);
INSERT INTO city (id, name, departmentId) VALUES (5411, 'Liborina', 5);
INSERT INTO city (id, name, departmentId) VALUES (5425, 'Maceo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5440, 'Marinilla', 5);
INSERT INTO city (id, name, departmentId) VALUES (5467, 'Montebello', 5);
INSERT INTO city (id, name, departmentId) VALUES (5475, 'Murindó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5480, 'Mutatá', 5);
INSERT INTO city (id, name, departmentId) VALUES (5483, 'Nariño', 5);
INSERT INTO city (id, name, departmentId) VALUES (5490, 'Necoclí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5495, 'Nechí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5501, 'Olaya', 5);
INSERT INTO city (id, name, departmentId) VALUES (5541, 'Peñol', 5);
INSERT INTO city (id, name, departmentId) VALUES (5543, 'Peque', 5);
INSERT INTO city (id, name, departmentId) VALUES (5576, 'Pueblorrico', 5);
INSERT INTO city (id, name, departmentId) VALUES (5579, 'Puerto Berrío', 5);
INSERT INTO city (id, name, departmentId) VALUES (5585, 'Puerto Nare', 5);
INSERT INTO city (id, name, departmentId) VALUES (5591, 'Puerto Triunfo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5604, 'Remedios', 5);
INSERT INTO city (id, name, departmentId) VALUES (5607, 'Retiro', 5);
INSERT INTO city (id, name, departmentId) VALUES (5615, 'Rionegro', 5);
INSERT INTO city (id, name, departmentId) VALUES (5628, 'Sabanalarga', 5);
INSERT INTO city (id, name, departmentId) VALUES (5631, 'Sabaneta', 5);
INSERT INTO city (id, name, departmentId) VALUES (5642, 'Salgar', 5);
INSERT INTO city (id, name, departmentId) VALUES (5647, 'San Andrés de Cuerquía', 5);
INSERT INTO city (id, name, departmentId) VALUES (5649, 'San Carlos', 5);
INSERT INTO city (id, name, departmentId) VALUES (5652, 'San Francisco', 5);
INSERT INTO city (id, name, departmentId) VALUES (5656, 'San Jerónimo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5658, 'San José de La Montaña', 5);
INSERT INTO city (id, name, departmentId) VALUES (5659, 'San Juan de Urabá', 5);
INSERT INTO city (id, name, departmentId) VALUES (5660, 'San Luis', 5);
INSERT INTO city (id, name, departmentId) VALUES (5664, 'San Pedro', 5);
INSERT INTO city (id, name, departmentId) VALUES (5665, 'San Pedro de Uraba', 5);
INSERT INTO city (id, name, departmentId) VALUES (5667, 'San Rafael', 5);
INSERT INTO city (id, name, departmentId) VALUES (5670, 'San Roque', 5);
INSERT INTO city (id, name, departmentId) VALUES (5674, 'San Vicente', 5);
INSERT INTO city (id, name, departmentId) VALUES (5679, 'Santa Bárbara', 5);
INSERT INTO city (id, name, departmentId) VALUES (5686, 'Santa Rosa de Osos', 5);
INSERT INTO city (id, name, departmentId) VALUES (5690, 'Santo Domingo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5697, 'El Santuario', 5);
INSERT INTO city (id, name, departmentId) VALUES (5736, 'Segovia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5756, 'Sonsón', 5);
INSERT INTO city (id, name, departmentId) VALUES (5761, 'Sopetrán', 5);
INSERT INTO city (id, name, departmentId) VALUES (5789, 'Támesis', 5);
INSERT INTO city (id, name, departmentId) VALUES (5790, 'Tarazá', 5);
INSERT INTO city (id, name, departmentId) VALUES (5792, 'Tarso', 5);
INSERT INTO city (id, name, departmentId) VALUES (5809, 'Titiribí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5819, 'Toledo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5837, 'Turbo', 5);
INSERT INTO city (id, name, departmentId) VALUES (5842, 'Uramita', 5);
INSERT INTO city (id, name, departmentId) VALUES (5847, 'Urrao', 5);
INSERT INTO city (id, name, departmentId) VALUES (5854, 'Valdivia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5856, 'Valparaíso', 5);
INSERT INTO city (id, name, departmentId) VALUES (5858, 'Vegachí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5861, 'Venecia', 5);
INSERT INTO city (id, name, departmentId) VALUES (5873, 'Vigía del Fuerte', 5);
INSERT INTO city (id, name, departmentId) VALUES (5885, 'Yalí', 5);
INSERT INTO city (id, name, departmentId) VALUES (5887, 'Yarumal', 5);
INSERT INTO city (id, name, departmentId) VALUES (5890, 'Yolombó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5893, 'Yondó', 5);
INSERT INTO city (id, name, departmentId) VALUES (5895, 'Zaragoza', 5);
INSERT INTO city (id, name, departmentId) VALUES (8001, 'Barranquilla', 8);
INSERT INTO city (id, name, departmentId) VALUES (8078, 'Baranoa', 8);
INSERT INTO city (id, name, departmentId) VALUES (8137, 'Campo de La Cruz', 8);
INSERT INTO city (id, name, departmentId) VALUES (8141, 'Candelaria', 8);
INSERT INTO city (id, name, departmentId) VALUES (8296, 'Galapa', 8);
INSERT INTO city (id, name, departmentId) VALUES (8372, 'Juan de Acosta', 8);
INSERT INTO city (id, name, departmentId) VALUES (8421, 'Luruaco', 8);
INSERT INTO city (id, name, departmentId) VALUES (8433, 'Malambo', 8);
INSERT INTO city (id, name, departmentId) VALUES (8436, 'Manatí', 8);
INSERT INTO city (id, name, departmentId) VALUES (8520, 'Palmar de Varela', 8);
INSERT INTO city (id, name, departmentId) VALUES (8549, 'Piojó', 8);
INSERT INTO city (id, name, departmentId) VALUES (8558, 'Polonuevo', 8);
INSERT INTO city (id, name, departmentId) VALUES (8560, 'Ponedera', 8);
INSERT INTO city (id, name, departmentId) VALUES (8573, 'Puerto Colombia', 8);
INSERT INTO city (id, name, departmentId) VALUES (8606, 'Repelón', 8);
INSERT INTO city (id, name, departmentId) VALUES (8634, 'Sabanagrande', 8);
INSERT INTO city (id, name, departmentId) VALUES (8638, 'Sabanalarga', 8);
INSERT INTO city (id, name, departmentId) VALUES (8675, 'Santa Lucía', 8);
INSERT INTO city (id, name, departmentId) VALUES (8685, 'Santo Tomás', 8);
INSERT INTO city (id, name, departmentId) VALUES (8758, 'Soledad', 8);
INSERT INTO city (id, name, departmentId) VALUES (8770, 'Suan', 8);
INSERT INTO city (id, name, departmentId) VALUES (8832, 'Tubará', 8);
INSERT INTO city (id, name, departmentId) VALUES (8849, 'Usiacurí', 8);
INSERT INTO city (id, name, departmentId) VALUES (11001, 'Bogotá D.C.', 11);
INSERT INTO city (id, name, departmentId) VALUES (13001, 'Cartagena', 13);
INSERT INTO city (id, name, departmentId) VALUES (13006, 'Achí', 13);
INSERT INTO city (id, name, departmentId) VALUES (13030, 'Altos del Rosario', 13);
INSERT INTO city (id, name, departmentId) VALUES (13042, 'Arenal', 13);
INSERT INTO city (id, name, departmentId) VALUES (13052, 'Arjona', 13);
INSERT INTO city (id, name, departmentId) VALUES (13062, 'Arroyohondo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13074, 'Barranco de Loba', 13);
INSERT INTO city (id, name, departmentId) VALUES (13140, 'Calamar', 13);
INSERT INTO city (id, name, departmentId) VALUES (13160, 'Cantagallo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13188, 'Cicuco', 13);
INSERT INTO city (id, name, departmentId) VALUES (13212, 'Córdoba', 13);
INSERT INTO city (id, name, departmentId) VALUES (13222, 'Clemencia', 13);
INSERT INTO city (id, name, departmentId) VALUES (13244, 'El Carmen de Bolívar', 13);
INSERT INTO city (id, name, departmentId) VALUES (13248, 'El Guamo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13268, 'El Peñón', 13);
INSERT INTO city (id, name, departmentId) VALUES (13300, 'Hatillo de Loba', 13);
INSERT INTO city (id, name, departmentId) VALUES (13430, 'Magangué', 13);
INSERT INTO city (id, name, departmentId) VALUES (13433, 'Mahates', 13);
INSERT INTO city (id, name, departmentId) VALUES (13440, 'Margarita', 13);
INSERT INTO city (id, name, departmentId) VALUES (13442, 'María la Baja', 13);
INSERT INTO city (id, name, departmentId) VALUES (13458, 'Montecristo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13468, 'Mompós', 13);
INSERT INTO city (id, name, departmentId) VALUES (13473, 'Morales', 13);
INSERT INTO city (id, name, departmentId) VALUES (13490, 'Norosí', 13);
INSERT INTO city (id, name, departmentId) VALUES (13549, 'Pinillos', 13);
INSERT INTO city (id, name, departmentId) VALUES (13580, 'Regidor', 13);
INSERT INTO city (id, name, departmentId) VALUES (13600, 'Río Viejo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13620, 'San Cristóbal', 13);
INSERT INTO city (id, name, departmentId) VALUES (13647, 'San Estanislao', 13);
INSERT INTO city (id, name, departmentId) VALUES (13650, 'San Fernando', 13);
INSERT INTO city (id, name, departmentId) VALUES (13654, 'San Jacinto', 13);
INSERT INTO city (id, name, departmentId) VALUES (13655, 'San Jacinto del Cauca', 13);
INSERT INTO city (id, name, departmentId) VALUES (13657, 'San Juan Nepomuceno', 13);
INSERT INTO city (id, name, departmentId) VALUES (13667, 'San Martín de Loba', 13);
INSERT INTO city (id, name, departmentId) VALUES (13670, 'San Pablo de Borbur', 13);
INSERT INTO city (id, name, departmentId) VALUES (13673, 'Santa Catalina', 13);
INSERT INTO city (id, name, departmentId) VALUES (13683, 'Santa Rosa', 13);
INSERT INTO city (id, name, departmentId) VALUES (13688, 'Santa Rosa del Sur', 13);
INSERT INTO city (id, name, departmentId) VALUES (13744, 'Simití', 13);
INSERT INTO city (id, name, departmentId) VALUES (13760, 'Soplaviento', 13);
INSERT INTO city (id, name, departmentId) VALUES (13780, 'Talaigua Nuevo', 13);
INSERT INTO city (id, name, departmentId) VALUES (13810, 'Tiquisio', 13);
INSERT INTO city (id, name, departmentId) VALUES (13836, 'Turbaco', 13);
INSERT INTO city (id, name, departmentId) VALUES (13838, 'Turbaná', 13);
INSERT INTO city (id, name, departmentId) VALUES (13873, 'Villanueva', 13);
INSERT INTO city (id, name, departmentId) VALUES (13894, 'Zambrano', 13);
INSERT INTO city (id, name, departmentId) VALUES (15001, 'Tunja', 15);
INSERT INTO city (id, name, departmentId) VALUES (15022, 'Almeida', 15);
INSERT INTO city (id, name, departmentId) VALUES (15047, 'Aquitania', 15);
INSERT INTO city (id, name, departmentId) VALUES (15051, 'Arcabuco', 15);
INSERT INTO city (id, name, departmentId) VALUES (15087, 'Belén', 15);
INSERT INTO city (id, name, departmentId) VALUES (15090, 'Berbeo', 15);
INSERT INTO city (id, name, departmentId) VALUES (15092, 'Betéitiva', 15);
INSERT INTO city (id, name, departmentId) VALUES (15097, 'Boavita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15104, 'Boyacá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15106, 'Briceño', 15);
INSERT INTO city (id, name, departmentId) VALUES (15109, 'Buena Vista', 15);
INSERT INTO city (id, name, departmentId) VALUES (15114, 'Busbanzá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15131, 'Caldas', 15);
INSERT INTO city (id, name, departmentId) VALUES (15135, 'Campohermoso', 15);
INSERT INTO city (id, name, departmentId) VALUES (15162, 'Cerinza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15172, 'Chinavita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15176, 'Chiquinquirá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15180, 'Chiscas', 15);
INSERT INTO city (id, name, departmentId) VALUES (15183, 'Chita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15185, 'Chitaraque', 15);
INSERT INTO city (id, name, departmentId) VALUES (15187, 'Chivatá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15189, 'Ciénega', 15);
INSERT INTO city (id, name, departmentId) VALUES (15204, 'Cómbita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15212, 'Coper', 15);
INSERT INTO city (id, name, departmentId) VALUES (15215, 'Corrales', 15);
INSERT INTO city (id, name, departmentId) VALUES (15218, 'Covarachía', 15);
INSERT INTO city (id, name, departmentId) VALUES (15223, 'Cubará', 15);
INSERT INTO city (id, name, departmentId) VALUES (15224, 'Cucaita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15226, 'Cuítiva', 15);
INSERT INTO city (id, name, departmentId) VALUES (15232, 'Chíquiza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15236, 'Chivor', 15);
INSERT INTO city (id, name, departmentId) VALUES (15238, 'Duitama', 15);
INSERT INTO city (id, name, departmentId) VALUES (15244, 'El Cocuy', 15);
INSERT INTO city (id, name, departmentId) VALUES (15248, 'El Espino', 15);
INSERT INTO city (id, name, departmentId) VALUES (15272, 'Firavitoba', 15);
INSERT INTO city (id, name, departmentId) VALUES (15276, 'Floresta', 15);
INSERT INTO city (id, name, departmentId) VALUES (15293, 'Gachantivá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15296, 'Gameza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15299, 'Garagoa', 15);
INSERT INTO city (id, name, departmentId) VALUES (15317, 'Guacamayas', 15);
INSERT INTO city (id, name, departmentId) VALUES (15322, 'Guateque', 15);
INSERT INTO city (id, name, departmentId) VALUES (15325, 'Guayatá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15332, 'Güicán', 15);
INSERT INTO city (id, name, departmentId) VALUES (15362, 'Iza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15367, 'Jenesano', 15);
INSERT INTO city (id, name, departmentId) VALUES (15368, 'Jericó', 15);
INSERT INTO city (id, name, departmentId) VALUES (15377, 'Labranzagrande', 15);
INSERT INTO city (id, name, departmentId) VALUES (15380, 'La Capilla', 15);
INSERT INTO city (id, name, departmentId) VALUES (15401, 'La Victoria', 15);
INSERT INTO city (id, name, departmentId) VALUES (15403, 'La Uvita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15407, 'Villa de Leyva', 15);
INSERT INTO city (id, name, departmentId) VALUES (15425, 'Macanal', 15);
INSERT INTO city (id, name, departmentId) VALUES (15442, 'Maripí', 15);
INSERT INTO city (id, name, departmentId) VALUES (15455, 'Miraflores', 15);
INSERT INTO city (id, name, departmentId) VALUES (15464, 'Mongua', 15);
INSERT INTO city (id, name, departmentId) VALUES (15466, 'Monguí', 15);
INSERT INTO city (id, name, departmentId) VALUES (15469, 'Moniquirá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15476, 'Motavita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15480, 'Muzo', 15);
INSERT INTO city (id, name, departmentId) VALUES (15491, 'Nobsa', 15);
INSERT INTO city (id, name, departmentId) VALUES (15494, 'Nuevo Colón', 15);
INSERT INTO city (id, name, departmentId) VALUES (15500, 'Oicatá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15507, 'Otanche', 15);
INSERT INTO city (id, name, departmentId) VALUES (15511, 'Pachavita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15514, 'Páez', 15);
INSERT INTO city (id, name, departmentId) VALUES (15516, 'Paipa', 15);
INSERT INTO city (id, name, departmentId) VALUES (15518, 'Pajarito', 15);
INSERT INTO city (id, name, departmentId) VALUES (15522, 'Panqueba', 15);
INSERT INTO city (id, name, departmentId) VALUES (15531, 'Pauna', 15);
INSERT INTO city (id, name, departmentId) VALUES (15533, 'Paya', 15);
INSERT INTO city (id, name, departmentId) VALUES (15537, 'Paz de Río', 15);
INSERT INTO city (id, name, departmentId) VALUES (15542, 'Pesca', 15);
INSERT INTO city (id, name, departmentId) VALUES (15550, 'Pisba', 15);
INSERT INTO city (id, name, departmentId) VALUES (15572, 'Puerto Boyacá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15580, 'Quípama', 15);
INSERT INTO city (id, name, departmentId) VALUES (15599, 'Ramiriquí', 15);
INSERT INTO city (id, name, departmentId) VALUES (15600, 'Ráquira', 15);
INSERT INTO city (id, name, departmentId) VALUES (15621, 'Rondón', 15);
INSERT INTO city (id, name, departmentId) VALUES (15632, 'Saboyá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15638, 'Sáchica', 15);
INSERT INTO city (id, name, departmentId) VALUES (15646, 'Samacá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15660, 'San Eduardo', 15);
INSERT INTO city (id, name, departmentId) VALUES (15664, 'San José de Pare', 15);
INSERT INTO city (id, name, departmentId) VALUES (15667, 'San Luis de Gaceno', 15);
INSERT INTO city (id, name, departmentId) VALUES (15673, 'San Mateo', 15);
INSERT INTO city (id, name, departmentId) VALUES (15676, 'San Miguel de Sema', 15);
INSERT INTO city (id, name, departmentId) VALUES (15681, 'San Pablo de Borbur', 15);
INSERT INTO city (id, name, departmentId) VALUES (15686, 'Santana', 15);
INSERT INTO city (id, name, departmentId) VALUES (15690, 'Santa María', 15);
INSERT INTO city (id, name, departmentId) VALUES (15693, 'Santa Rosa de Viterbo', 15);
INSERT INTO city (id, name, departmentId) VALUES (15696, 'Santa Sofía', 15);
INSERT INTO city (id, name, departmentId) VALUES (15720, 'Sativanorte', 15);
INSERT INTO city (id, name, departmentId) VALUES (15723, 'Sativasur', 15);
INSERT INTO city (id, name, departmentId) VALUES (15740, 'Siachoque', 15);
INSERT INTO city (id, name, departmentId) VALUES (15753, 'Soatá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15755, 'Socotá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15757, 'Socha', 15);
INSERT INTO city (id, name, departmentId) VALUES (15759, 'Sogamoso', 15);
INSERT INTO city (id, name, departmentId) VALUES (15761, 'Somondoco', 15);
INSERT INTO city (id, name, departmentId) VALUES (15762, 'Sora', 15);
INSERT INTO city (id, name, departmentId) VALUES (15763, 'Sotaquirá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15764, 'Soracá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15774, 'Susacón', 15);
INSERT INTO city (id, name, departmentId) VALUES (15776, 'Sutamarchán', 15);
INSERT INTO city (id, name, departmentId) VALUES (15778, 'Sutatenza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15790, 'Tasco', 15);
INSERT INTO city (id, name, departmentId) VALUES (15798, 'Tenza', 15);
INSERT INTO city (id, name, departmentId) VALUES (15804, 'Tibaná', 15);
INSERT INTO city (id, name, departmentId) VALUES (15806, 'Tibasosa', 15);
INSERT INTO city (id, name, departmentId) VALUES (15808, 'Tinjacá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15810, 'Tipacoque', 15);
INSERT INTO city (id, name, departmentId) VALUES (15814, 'Toca', 15);
INSERT INTO city (id, name, departmentId) VALUES (15816, 'Togüí', 15);
INSERT INTO city (id, name, departmentId) VALUES (15820, 'Tópaga', 15);
INSERT INTO city (id, name, departmentId) VALUES (15822, 'Tota', 15);
INSERT INTO city (id, name, departmentId) VALUES (15832, 'Tununguá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15835, 'Turmequé', 15);
INSERT INTO city (id, name, departmentId) VALUES (15837, 'Tuta', 15);
INSERT INTO city (id, name, departmentId) VALUES (15839, 'Tutazá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15842, 'Umbita', 15);
INSERT INTO city (id, name, departmentId) VALUES (15861, 'Ventaquemada', 15);
INSERT INTO city (id, name, departmentId) VALUES (15879, 'Viracachá', 15);
INSERT INTO city (id, name, departmentId) VALUES (15897, 'Zetaquira', 15);
INSERT INTO city (id, name, departmentId) VALUES (17001, 'Manizales', 17);
INSERT INTO city (id, name, departmentId) VALUES (17013, 'Aguadas', 17);
INSERT INTO city (id, name, departmentId) VALUES (17042, 'Anserma', 17);
INSERT INTO city (id, name, departmentId) VALUES (17050, 'Aranzazu', 17);
INSERT INTO city (id, name, departmentId) VALUES (17088, 'Belalcázar', 17);
INSERT INTO city (id, name, departmentId) VALUES (17174, 'Chinchiná', 17);
INSERT INTO city (id, name, departmentId) VALUES (17272, 'Filadelfia', 17);
INSERT INTO city (id, name, departmentId) VALUES (17380, 'La Dorada', 17);
INSERT INTO city (id, name, departmentId) VALUES (17388, 'La Merced', 17);
INSERT INTO city (id, name, departmentId) VALUES (17433, 'Manzanares', 17);
INSERT INTO city (id, name, departmentId) VALUES (17442, 'Marmato', 17);
INSERT INTO city (id, name, departmentId) VALUES (17444, 'Marquetalia', 17);
INSERT INTO city (id, name, departmentId) VALUES (17446, 'Marulanda', 17);
INSERT INTO city (id, name, departmentId) VALUES (17486, 'Neira', 17);
INSERT INTO city (id, name, departmentId) VALUES (17495, 'Norcasia', 17);
INSERT INTO city (id, name, departmentId) VALUES (17513, 'Pácora', 17);
INSERT INTO city (id, name, departmentId) VALUES (17524, 'Palestina', 17);
INSERT INTO city (id, name, departmentId) VALUES (17541, 'Pensilvania', 17);
INSERT INTO city (id, name, departmentId) VALUES (17614, 'Riosucio', 17);
INSERT INTO city (id, name, departmentId) VALUES (17616, 'Risaralda', 17);
INSERT INTO city (id, name, departmentId) VALUES (17653, 'Salamina', 17);
INSERT INTO city (id, name, departmentId) VALUES (17662, 'Samaná', 17);
INSERT INTO city (id, name, departmentId) VALUES (17665, 'San José', 17);
INSERT INTO city (id, name, departmentId) VALUES (17777, 'Supía', 17);
INSERT INTO city (id, name, departmentId) VALUES (17867, 'Victoria', 17);
INSERT INTO city (id, name, departmentId) VALUES (17873, 'Villamaría', 17);
INSERT INTO city (id, name, departmentId) VALUES (17877, 'Viterbo', 17);
INSERT INTO city (id, name, departmentId) VALUES (18001, 'Florencia', 18);
INSERT INTO city (id, name, departmentId) VALUES (18029, 'Albania', 18);
INSERT INTO city (id, name, departmentId) VALUES (18094, 'Belén de Los Andaquies', 18);
INSERT INTO city (id, name, departmentId) VALUES (18150, 'Cartagena del Chairá', 18);
INSERT INTO city (id, name, departmentId) VALUES (18205, 'Curillo', 18);
INSERT INTO city (id, name, departmentId) VALUES (18247, 'El Doncello', 18);
INSERT INTO city (id, name, departmentId) VALUES (18256, 'El Paujil', 18);
INSERT INTO city (id, name, departmentId) VALUES (18410, 'La Montañita', 18);
INSERT INTO city (id, name, departmentId) VALUES (18460, 'Milán', 18);
INSERT INTO city (id, name, departmentId) VALUES (18479, 'Morelia', 18);
INSERT INTO city (id, name, departmentId) VALUES (18592, 'Puerto Rico', 18);
INSERT INTO city (id, name, departmentId) VALUES (18610, 'San José del Fragua', 18);
INSERT INTO city (id, name, departmentId) VALUES (18753, 'San Vicente del Caguán', 18);
INSERT INTO city (id, name, departmentId) VALUES (18756, 'Solano', 18);
INSERT INTO city (id, name, departmentId) VALUES (18785, 'Solita', 18);
INSERT INTO city (id, name, departmentId) VALUES (18860, 'Valparaíso', 18);
INSERT INTO city (id, name, departmentId) VALUES (19001, 'Popayán', 19);
INSERT INTO city (id, name, departmentId) VALUES (19022, 'Almaguer', 19);
INSERT INTO city (id, name, departmentId) VALUES (19050, 'Argelia', 19);
INSERT INTO city (id, name, departmentId) VALUES (19075, 'Balboa', 19);
INSERT INTO city (id, name, departmentId) VALUES (19100, 'Bolívar', 19);
INSERT INTO city (id, name, departmentId) VALUES (19110, 'Buenos Aires', 19);
INSERT INTO city (id, name, departmentId) VALUES (19130, 'Cajibío', 19);
INSERT INTO city (id, name, departmentId) VALUES (19137, 'Caldono', 19);
INSERT INTO city (id, name, departmentId) VALUES (19142, 'Caloto', 19);
INSERT INTO city (id, name, departmentId) VALUES (19212, 'Corinto', 19);
INSERT INTO city (id, name, departmentId) VALUES (19256, 'El Tambo', 19);
INSERT INTO city (id, name, departmentId) VALUES (19290, 'Florencia', 19);
INSERT INTO city (id, name, departmentId) VALUES (19300, 'Guachené', 19);
INSERT INTO city (id, name, departmentId) VALUES (19318, 'Guapi', 19);
INSERT INTO city (id, name, departmentId) VALUES (19355, 'Inzá', 19);
INSERT INTO city (id, name, departmentId) VALUES (19364, 'Jambaló', 19);
INSERT INTO city (id, name, departmentId) VALUES (19392, 'La Sierra', 19);
INSERT INTO city (id, name, departmentId) VALUES (19397, 'La Vega', 19);
INSERT INTO city (id, name, departmentId) VALUES (19418, 'López', 19);
INSERT INTO city (id, name, departmentId) VALUES (19450, 'Mercaderes', 19);
INSERT INTO city (id, name, departmentId) VALUES (19455, 'Miranda', 19);
INSERT INTO city (id, name, departmentId) VALUES (19473, 'Morales', 19);
INSERT INTO city (id, name, departmentId) VALUES (19513, 'Padilla', 19);
INSERT INTO city (id, name, departmentId) VALUES (19517, 'Páez', 19);
INSERT INTO city (id, name, departmentId) VALUES (19532, 'Patía', 19);
INSERT INTO city (id, name, departmentId) VALUES (19533, 'Piamonte', 19);
INSERT INTO city (id, name, departmentId) VALUES (19548, 'Piendamó', 19);
INSERT INTO city (id, name, departmentId) VALUES (19573, 'Puerto Tejada', 19);
INSERT INTO city (id, name, departmentId) VALUES (19585, 'Puracé', 19);
INSERT INTO city (id, name, departmentId) VALUES (19622, 'Rosas', 19);
INSERT INTO city (id, name, departmentId) VALUES (19693, 'San Sebastián', 19);
INSERT INTO city (id, name, departmentId) VALUES (19698, 'Santander de Quilichao', 19);
INSERT INTO city (id, name, departmentId) VALUES (19701, 'Santa Rosa', 19);
INSERT INTO city (id, name, departmentId) VALUES (19743, 'Silvia', 19);
INSERT INTO city (id, name, departmentId) VALUES (19760, 'Sotara', 19);
INSERT INTO city (id, name, departmentId) VALUES (19780, 'Suárez', 19);
INSERT INTO city (id, name, departmentId) VALUES (19785, 'Sucre', 19);
INSERT INTO city (id, name, departmentId) VALUES (19807, 'Timbío', 19);
INSERT INTO city (id, name, departmentId) VALUES (19809, 'Timbiquí', 19);
INSERT INTO city (id, name, departmentId) VALUES (19821, 'Toribio', 19);
INSERT INTO city (id, name, departmentId) VALUES (19824, 'Totoró', 19);
INSERT INTO city (id, name, departmentId) VALUES (19845, 'Villa Rica', 19);
INSERT INTO city (id, name, departmentId) VALUES (20001, 'Valledupar', 20);
INSERT INTO city (id, name, departmentId) VALUES (20011, 'Aguachica', 20);
INSERT INTO city (id, name, departmentId) VALUES (20013, 'Agustín Codazzi', 20);
INSERT INTO city (id, name, departmentId) VALUES (20032, 'Astrea', 20);
INSERT INTO city (id, name, departmentId) VALUES (20045, 'Becerril', 20);
INSERT INTO city (id, name, departmentId) VALUES (20060, 'Bosconia', 20);
INSERT INTO city (id, name, departmentId) VALUES (20175, 'Chimichagua', 20);
INSERT INTO city (id, name, departmentId) VALUES (20178, 'Chiriguaná', 20);
INSERT INTO city (id, name, departmentId) VALUES (20228, 'Curumaní', 20);
INSERT INTO city (id, name, departmentId) VALUES (20238, 'El Copey', 20);
INSERT INTO city (id, name, departmentId) VALUES (20250, 'El Paso', 20);
INSERT INTO city (id, name, departmentId) VALUES (20295, 'Gamarra', 20);
INSERT INTO city (id, name, departmentId) VALUES (20310, 'González', 20);
INSERT INTO city (id, name, departmentId) VALUES (20383, 'La Gloria', 20);
INSERT INTO city (id, name, departmentId) VALUES (20400, 'La Jagua de Ibirico', 20);
INSERT INTO city (id, name, departmentId) VALUES (20443, 'Manaure', 20);
INSERT INTO city (id, name, departmentId) VALUES (20517, 'Pailitas', 20);
INSERT INTO city (id, name, departmentId) VALUES (20550, 'Pelaya', 20);
INSERT INTO city (id, name, departmentId) VALUES (20570, 'Pueblo Bello', 20);
INSERT INTO city (id, name, departmentId) VALUES (20614, 'Río de Oro', 20);
INSERT INTO city (id, name, departmentId) VALUES (20621, 'La Paz', 20);
INSERT INTO city (id, name, departmentId) VALUES (20710, 'San Alberto', 20);
INSERT INTO city (id, name, departmentId) VALUES (20750, 'San Diego', 20);
INSERT INTO city (id, name, departmentId) VALUES (20770, 'San Martín', 20);
INSERT INTO city (id, name, departmentId) VALUES (20787, 'Tamalameque', 20);
INSERT INTO city (id, name, departmentId) VALUES (23001, 'Montería', 23);
INSERT INTO city (id, name, departmentId) VALUES (23068, 'Ayapel', 23);
INSERT INTO city (id, name, departmentId) VALUES (23079, 'Buenavista', 23);
INSERT INTO city (id, name, departmentId) VALUES (23090, 'Canalete', 23);
INSERT INTO city (id, name, departmentId) VALUES (23162, 'Cereté', 23);
INSERT INTO city (id, name, departmentId) VALUES (23168, 'Chimá', 23);
INSERT INTO city (id, name, departmentId) VALUES (23182, 'Chinú', 23);
INSERT INTO city (id, name, departmentId) VALUES (23189, 'Ciénaga de Oro', 23);
INSERT INTO city (id, name, departmentId) VALUES (23300, 'Cotorra', 23);
INSERT INTO city (id, name, departmentId) VALUES (23350, 'La Apartada', 23);
INSERT INTO city (id, name, departmentId) VALUES (23417, 'Lorica', 23);
INSERT INTO city (id, name, departmentId) VALUES (23419, 'Los Córdobas', 23);
INSERT INTO city (id, name, departmentId) VALUES (23464, 'Momil', 23);
INSERT INTO city (id, name, departmentId) VALUES (23466, 'Montelíbano', 23);
INSERT INTO city (id, name, departmentId) VALUES (23500, 'Moñitos', 23);
INSERT INTO city (id, name, departmentId) VALUES (23555, 'Planeta Rica', 23);
INSERT INTO city (id, name, departmentId) VALUES (23570, 'Pueblo Nuevo', 23);
INSERT INTO city (id, name, departmentId) VALUES (23574, 'Puerto Escondido', 23);
INSERT INTO city (id, name, departmentId) VALUES (23580, 'Puerto Libertador', 23);
INSERT INTO city (id, name, departmentId) VALUES (23586, 'Purísima', 23);
INSERT INTO city (id, name, departmentId) VALUES (23660, 'Sahagún', 23);
INSERT INTO city (id, name, departmentId) VALUES (23670, 'San Andrés Sotavento', 23);
INSERT INTO city (id, name, departmentId) VALUES (23672, 'San Antero', 23);
INSERT INTO city (id, name, departmentId) VALUES (23675, 'San Bernardo del Viento', 23);
INSERT INTO city (id, name, departmentId) VALUES (23678, 'San Carlos', 23);
INSERT INTO city (id, name, departmentId) VALUES (23682, 'San José de Uré', 23);
INSERT INTO city (id, name, departmentId) VALUES (23686, 'San Pelayo', 23);
INSERT INTO city (id, name, departmentId) VALUES (23807, 'Tierralta', 23);
INSERT INTO city (id, name, departmentId) VALUES (23815, 'Tuchín', 23);
INSERT INTO city (id, name, departmentId) VALUES (23855, 'Valencia', 23);
INSERT INTO city (id, name, departmentId) VALUES (25001, 'Agua de Dios', 25);
INSERT INTO city (id, name, departmentId) VALUES (25019, 'Albán', 25);
INSERT INTO city (id, name, departmentId) VALUES (25035, 'Anapoima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25040, 'Anolaima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25053, 'Arbeláez', 25);
INSERT INTO city (id, name, departmentId) VALUES (25086, 'Beltrán', 25);
INSERT INTO city (id, name, departmentId) VALUES (25095, 'Bituima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25099, 'Bojacá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25120, 'Cabrera', 25);
INSERT INTO city (id, name, departmentId) VALUES (25123, 'Cachipay', 25);
INSERT INTO city (id, name, departmentId) VALUES (25126, 'Cajicá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25148, 'Caparrapí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25151, 'Caqueza', 25);
INSERT INTO city (id, name, departmentId) VALUES (25154, 'Carmen de Carupa', 25);
INSERT INTO city (id, name, departmentId) VALUES (25168, 'Chaguaní', 25);
INSERT INTO city (id, name, departmentId) VALUES (25175, 'Chía', 25);
INSERT INTO city (id, name, departmentId) VALUES (25178, 'Chipaque', 25);
INSERT INTO city (id, name, departmentId) VALUES (25181, 'Choachí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25183, 'Chocontá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25200, 'Cogua', 25);
INSERT INTO city (id, name, departmentId) VALUES (25214, 'Cota', 25);
INSERT INTO city (id, name, departmentId) VALUES (25224, 'Cucunubá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25245, 'El Colegio', 25);
INSERT INTO city (id, name, departmentId) VALUES (25258, 'El Peñón', 25);
INSERT INTO city (id, name, departmentId) VALUES (25260, 'El Rosal', 25);
INSERT INTO city (id, name, departmentId) VALUES (25269, 'Facatativá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25279, 'Fomeque', 25);
INSERT INTO city (id, name, departmentId) VALUES (25281, 'Fosca', 25);
INSERT INTO city (id, name, departmentId) VALUES (25286, 'Funza', 25);
INSERT INTO city (id, name, departmentId) VALUES (25288, 'Fúquene', 25);
INSERT INTO city (id, name, departmentId) VALUES (25290, 'Fusagasugá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25293, 'Gachala', 25);
INSERT INTO city (id, name, departmentId) VALUES (25295, 'Gachancipá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25297, 'Gachetá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25299, 'Gama', 25);
INSERT INTO city (id, name, departmentId) VALUES (25307, 'Girardot', 25);
INSERT INTO city (id, name, departmentId) VALUES (25312, 'Granada', 25);
INSERT INTO city (id, name, departmentId) VALUES (25317, 'Guachetá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25320, 'Guaduas', 25);
INSERT INTO city (id, name, departmentId) VALUES (25322, 'Guasca', 25);
INSERT INTO city (id, name, departmentId) VALUES (25324, 'Guataquí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25326, 'Guatavita', 25);
INSERT INTO city (id, name, departmentId) VALUES (25328, 'Guayabal de Siquima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25335, 'Guayabetal', 25);
INSERT INTO city (id, name, departmentId) VALUES (25339, 'Gutiérrez', 25);
INSERT INTO city (id, name, departmentId) VALUES (25368, 'Jerusalén', 25);
INSERT INTO city (id, name, departmentId) VALUES (25372, 'Junín', 25);
INSERT INTO city (id, name, departmentId) VALUES (25377, 'La Calera', 25);
INSERT INTO city (id, name, departmentId) VALUES (25386, 'La Mesa', 25);
INSERT INTO city (id, name, departmentId) VALUES (25394, 'La Palma', 25);
INSERT INTO city (id, name, departmentId) VALUES (25398, 'La Peña', 25);
INSERT INTO city (id, name, departmentId) VALUES (25402, 'La Vega', 25);
INSERT INTO city (id, name, departmentId) VALUES (25407, 'Lenguazaque', 25);
INSERT INTO city (id, name, departmentId) VALUES (25426, 'Macheta', 25);
INSERT INTO city (id, name, departmentId) VALUES (25430, 'Madrid', 25);
INSERT INTO city (id, name, departmentId) VALUES (25436, 'Manta', 25);
INSERT INTO city (id, name, departmentId) VALUES (25438, 'Medina', 25);
INSERT INTO city (id, name, departmentId) VALUES (25473, 'Mosquera', 25);
INSERT INTO city (id, name, departmentId) VALUES (25483, 'Nariño', 25);
INSERT INTO city (id, name, departmentId) VALUES (25486, 'Nemocón', 25);
INSERT INTO city (id, name, departmentId) VALUES (25488, 'Nilo', 25);
INSERT INTO city (id, name, departmentId) VALUES (25489, 'Nimaima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25491, 'Nocaima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25506, 'Venecia', 25);
INSERT INTO city (id, name, departmentId) VALUES (25513, 'Pacho', 25);
INSERT INTO city (id, name, departmentId) VALUES (25518, 'Paime', 25);
INSERT INTO city (id, name, departmentId) VALUES (25524, 'Pandi', 25);
INSERT INTO city (id, name, departmentId) VALUES (25530, 'Paratebueno', 25);
INSERT INTO city (id, name, departmentId) VALUES (25535, 'Pasca', 25);
INSERT INTO city (id, name, departmentId) VALUES (25572, 'Puerto Salgar', 25);
INSERT INTO city (id, name, departmentId) VALUES (25580, 'Pulí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25592, 'Quebradanegra', 25);
INSERT INTO city (id, name, departmentId) VALUES (25594, 'Quetame', 25);
INSERT INTO city (id, name, departmentId) VALUES (25596, 'Quipile', 25);
INSERT INTO city (id, name, departmentId) VALUES (25599, 'Apulo', 25);
INSERT INTO city (id, name, departmentId) VALUES (25612, 'Ricaurte', 25);
INSERT INTO city (id, name, departmentId) VALUES (25645, 'San Antonio del Tequendama', 25);
INSERT INTO city (id, name, departmentId) VALUES (25649, 'San Bernardo', 25);
INSERT INTO city (id, name, departmentId) VALUES (25653, 'San Cayetano', 25);
INSERT INTO city (id, name, departmentId) VALUES (25658, 'San Francisco', 25);
INSERT INTO city (id, name, departmentId) VALUES (25662, 'San Juan de Río Seco', 25);
INSERT INTO city (id, name, departmentId) VALUES (25718, 'Sasaima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25736, 'Sesquilé', 25);
INSERT INTO city (id, name, departmentId) VALUES (25740, 'Sibaté', 25);
INSERT INTO city (id, name, departmentId) VALUES (25743, 'Silvania', 25);
INSERT INTO city (id, name, departmentId) VALUES (25745, 'Simijaca', 25);
INSERT INTO city (id, name, departmentId) VALUES (25754, 'Soacha', 25);
INSERT INTO city (id, name, departmentId) VALUES (25758, 'Sopó', 25);
INSERT INTO city (id, name, departmentId) VALUES (25769, 'Subachoque', 25);
INSERT INTO city (id, name, departmentId) VALUES (25772, 'Suesca', 25);
INSERT INTO city (id, name, departmentId) VALUES (25777, 'Supatá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25779, 'Susa', 25);
INSERT INTO city (id, name, departmentId) VALUES (25781, 'Sutatausa', 25);
INSERT INTO city (id, name, departmentId) VALUES (25785, 'Tabio', 25);
INSERT INTO city (id, name, departmentId) VALUES (25793, 'Tausa', 25);
INSERT INTO city (id, name, departmentId) VALUES (25797, 'Tena', 25);
INSERT INTO city (id, name, departmentId) VALUES (25799, 'Tenjo', 25);
INSERT INTO city (id, name, departmentId) VALUES (25805, 'Tibacuy', 25);
INSERT INTO city (id, name, departmentId) VALUES (25807, 'Tibirita', 25);
INSERT INTO city (id, name, departmentId) VALUES (25815, 'Tocaima', 25);
INSERT INTO city (id, name, departmentId) VALUES (25817, 'Tocancipá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25823, 'Topaipí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25839, 'Ubalá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25841, 'Ubaque', 25);
INSERT INTO city (id, name, departmentId) VALUES (25843, 'Villa de San Diego de Ubate', 25);
INSERT INTO city (id, name, departmentId) VALUES (25845, 'Une', 25);
INSERT INTO city (id, name, departmentId) VALUES (25851, 'Útica', 25);
INSERT INTO city (id, name, departmentId) VALUES (25862, 'Vergara', 25);
INSERT INTO city (id, name, departmentId) VALUES (25867, 'Vianí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25871, 'Villagómez', 25);
INSERT INTO city (id, name, departmentId) VALUES (25873, 'Villapinzón', 25);
INSERT INTO city (id, name, departmentId) VALUES (25875, 'Villeta', 25);
INSERT INTO city (id, name, departmentId) VALUES (25878, 'Viotá', 25);
INSERT INTO city (id, name, departmentId) VALUES (25885, 'Yacopí', 25);
INSERT INTO city (id, name, departmentId) VALUES (25898, 'Zipacón', 25);
INSERT INTO city (id, name, departmentId) VALUES (25899, 'Zipaquirá', 25);
INSERT INTO city (id, name, departmentId) VALUES (27001, 'Quibdó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27006, 'Acandí', 27);
INSERT INTO city (id, name, departmentId) VALUES (27025, 'Alto Baudo', 27);
INSERT INTO city (id, name, departmentId) VALUES (27050, 'Atrato', 27);
INSERT INTO city (id, name, departmentId) VALUES (27073, 'Bagadó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27075, 'Bahía Solano', 27);
INSERT INTO city (id, name, departmentId) VALUES (27077, 'Bajo Baudó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27086, 'Belén de Bajira', 27);
INSERT INTO city (id, name, departmentId) VALUES (27099, 'Bojaya', 27);
INSERT INTO city (id, name, departmentId) VALUES (27135, 'El Cantón del San Pablo', 27);
INSERT INTO city (id, name, departmentId) VALUES (27150, 'Carmen del Darien', 27);
INSERT INTO city (id, name, departmentId) VALUES (27160, 'Cértegui', 27);
INSERT INTO city (id, name, departmentId) VALUES (27205, 'Condoto', 27);
INSERT INTO city (id, name, departmentId) VALUES (27245, 'El Carmen de Atrato', 27);
INSERT INTO city (id, name, departmentId) VALUES (27250, 'El Litoral del San Juan', 27);
INSERT INTO city (id, name, departmentId) VALUES (27361, 'Istmina', 27);
INSERT INTO city (id, name, departmentId) VALUES (27372, 'Juradó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27413, 'Lloró', 27);
INSERT INTO city (id, name, departmentId) VALUES (27425, 'Medio Atrato', 27);
INSERT INTO city (id, name, departmentId) VALUES (27430, 'Medio Baudó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27450, 'Medio San Juan', 27);
INSERT INTO city (id, name, departmentId) VALUES (27491, 'Nóvita', 27);
INSERT INTO city (id, name, departmentId) VALUES (27495, 'Nuquí', 27);
INSERT INTO city (id, name, departmentId) VALUES (27580, 'Río Iro', 27);
INSERT INTO city (id, name, departmentId) VALUES (27600, 'Río Quito', 27);
INSERT INTO city (id, name, departmentId) VALUES (27615, 'Riosucio', 27);
INSERT INTO city (id, name, departmentId) VALUES (27660, 'San José del Palmar', 27);
INSERT INTO city (id, name, departmentId) VALUES (27745, 'Sipí', 27);
INSERT INTO city (id, name, departmentId) VALUES (27787, 'Tadó', 27);
INSERT INTO city (id, name, departmentId) VALUES (27800, 'Unguía', 27);
INSERT INTO city (id, name, departmentId) VALUES (27810, 'Unión Panamericana', 27);
INSERT INTO city (id, name, departmentId) VALUES (41001, 'Neiva', 41);
INSERT INTO city (id, name, departmentId) VALUES (41006, 'Acevedo', 41);
INSERT INTO city (id, name, departmentId) VALUES (41013, 'Agrado', 41);
INSERT INTO city (id, name, departmentId) VALUES (41016, 'Aipe', 41);
INSERT INTO city (id, name, departmentId) VALUES (41020, 'Algeciras', 41);
INSERT INTO city (id, name, departmentId) VALUES (41026, 'Altamira', 41);
INSERT INTO city (id, name, departmentId) VALUES (41078, 'Baraya', 41);
INSERT INTO city (id, name, departmentId) VALUES (41132, 'Campoalegre', 41);
INSERT INTO city (id, name, departmentId) VALUES (41206, 'Colombia', 41);
INSERT INTO city (id, name, departmentId) VALUES (41244, 'Elías', 41);
INSERT INTO city (id, name, departmentId) VALUES (41298, 'Garzón', 41);
INSERT INTO city (id, name, departmentId) VALUES (41306, 'Gigante', 41);
INSERT INTO city (id, name, departmentId) VALUES (41319, 'Guadalupe', 41);
INSERT INTO city (id, name, departmentId) VALUES (41349, 'Hobo', 41);
INSERT INTO city (id, name, departmentId) VALUES (41357, 'Iquira', 41);
INSERT INTO city (id, name, departmentId) VALUES (41359, 'Isnos', 41);
INSERT INTO city (id, name, departmentId) VALUES (41378, 'La Argentina', 41);
INSERT INTO city (id, name, departmentId) VALUES (41396, 'La Plata', 41);
INSERT INTO city (id, name, departmentId) VALUES (41483, 'Nátaga', 41);
INSERT INTO city (id, name, departmentId) VALUES (41503, 'Oporapa', 41);
INSERT INTO city (id, name, departmentId) VALUES (41518, 'Paicol', 41);
INSERT INTO city (id, name, departmentId) VALUES (41524, 'Palermo', 41);
INSERT INTO city (id, name, departmentId) VALUES (41530, 'Palestina', 41);
INSERT INTO city (id, name, departmentId) VALUES (41548, 'Pital', 41);
INSERT INTO city (id, name, departmentId) VALUES (41551, 'Pitalito', 41);
INSERT INTO city (id, name, departmentId) VALUES (41615, 'Rivera', 41);
INSERT INTO city (id, name, departmentId) VALUES (41660, 'Saladoblanco', 41);
INSERT INTO city (id, name, departmentId) VALUES (41668, 'San Agustín', 41);
INSERT INTO city (id, name, departmentId) VALUES (41676, 'Santa María', 41);
INSERT INTO city (id, name, departmentId) VALUES (41770, 'Suaza', 41);
INSERT INTO city (id, name, departmentId) VALUES (41791, 'Tarqui', 41);
INSERT INTO city (id, name, departmentId) VALUES (41797, 'Tesalia', 41);
INSERT INTO city (id, name, departmentId) VALUES (41799, 'Tello', 41);
INSERT INTO city (id, name, departmentId) VALUES (41801, 'Teruel', 41);
INSERT INTO city (id, name, departmentId) VALUES (41807, 'Timaná', 41);
INSERT INTO city (id, name, departmentId) VALUES (41872, 'Villavieja', 41);
INSERT INTO city (id, name, departmentId) VALUES (41885, 'Yaguará', 41);
INSERT INTO city (id, name, departmentId) VALUES (44001, 'Riohacha', 44);
INSERT INTO city (id, name, departmentId) VALUES (44035, 'Albania', 44);
INSERT INTO city (id, name, departmentId) VALUES (44078, 'Barrancas', 44);
INSERT INTO city (id, name, departmentId) VALUES (44090, 'Dibula', 44);
INSERT INTO city (id, name, departmentId) VALUES (44098, 'Distracción', 44);
INSERT INTO city (id, name, departmentId) VALUES (44110, 'El Molino', 44);
INSERT INTO city (id, name, departmentId) VALUES (44279, 'Fonseca', 44);
INSERT INTO city (id, name, departmentId) VALUES (44378, 'Hatonuevo', 44);
INSERT INTO city (id, name, departmentId) VALUES (44420, 'La Jagua del Pilar', 44);
INSERT INTO city (id, name, departmentId) VALUES (44430, 'Maicao', 44);
INSERT INTO city (id, name, departmentId) VALUES (44560, 'Manaure', 44);
INSERT INTO city (id, name, departmentId) VALUES (44650, 'San Juan del Cesar', 44);
INSERT INTO city (id, name, departmentId) VALUES (44847, 'Uribia', 44);
INSERT INTO city (id, name, departmentId) VALUES (44855, 'Urumita', 44);
INSERT INTO city (id, name, departmentId) VALUES (44874, 'Villanueva', 44);
INSERT INTO city (id, name, departmentId) VALUES (47001, 'Santa Marta', 47);
INSERT INTO city (id, name, departmentId) VALUES (47030, 'Algarrobo', 47);
INSERT INTO city (id, name, departmentId) VALUES (47053, 'Aracataca', 47);
INSERT INTO city (id, name, departmentId) VALUES (47058, 'Ariguaní', 47);
INSERT INTO city (id, name, departmentId) VALUES (47161, 'Cerro San Antonio', 47);
INSERT INTO city (id, name, departmentId) VALUES (47170, 'Chivolo', 47);
INSERT INTO city (id, name, departmentId) VALUES (47189, 'Ciénaga', 47);
INSERT INTO city (id, name, departmentId) VALUES (47205, 'Concordia', 47);
INSERT INTO city (id, name, departmentId) VALUES (47245, 'El Banco', 47);
INSERT INTO city (id, name, departmentId) VALUES (47258, 'El Piñon', 47);
INSERT INTO city (id, name, departmentId) VALUES (47268, 'El Retén', 47);
INSERT INTO city (id, name, departmentId) VALUES (47288, 'Fundación', 47);
INSERT INTO city (id, name, departmentId) VALUES (47318, 'Guamal', 47);
INSERT INTO city (id, name, departmentId) VALUES (47460, 'Nueva Granada', 47);
INSERT INTO city (id, name, departmentId) VALUES (47541, 'Pedraza', 47);
INSERT INTO city (id, name, departmentId) VALUES (47545, 'Pijiño del Carmen', 47);
INSERT INTO city (id, name, departmentId) VALUES (47551, 'Pivijay', 47);
INSERT INTO city (id, name, departmentId) VALUES (47555, 'Plato', 47);
INSERT INTO city (id, name, departmentId) VALUES (47570, 'Pueblo Viejo', 47);
INSERT INTO city (id, name, departmentId) VALUES (47605, 'Remolino', 47);
INSERT INTO city (id, name, departmentId) VALUES (47660, 'Sabanas de San Angel', 47);
INSERT INTO city (id, name, departmentId) VALUES (47675, 'Salamina', 47);
INSERT INTO city (id, name, departmentId) VALUES (47692, 'San Sebastián de Buenavista', 47);
INSERT INTO city (id, name, departmentId) VALUES (47703, 'San Zenón', 47);
INSERT INTO city (id, name, departmentId) VALUES (47707, 'Santa Ana', 47);
INSERT INTO city (id, name, departmentId) VALUES (47720, 'Santa Bárbara de Pinto', 47);
INSERT INTO city (id, name, departmentId) VALUES (47745, 'Sitionuevo', 47);
INSERT INTO city (id, name, departmentId) VALUES (47798, 'Tenerife', 47);
INSERT INTO city (id, name, departmentId) VALUES (47960, 'Zapayán', 47);
INSERT INTO city (id, name, departmentId) VALUES (47980, 'Zona Bananera', 47);
INSERT INTO city (id, name, departmentId) VALUES (50001, 'Villavicencio', 50);
INSERT INTO city (id, name, departmentId) VALUES (50006, 'Acacias', 50);
INSERT INTO city (id, name, departmentId) VALUES (50110, 'Barranca de Upía', 50);
INSERT INTO city (id, name, departmentId) VALUES (50124, 'Cabuyaro', 50);
INSERT INTO city (id, name, departmentId) VALUES (50150, 'Castilla la Nueva', 50);
INSERT INTO city (id, name, departmentId) VALUES (50223, 'Cubarral', 50);
INSERT INTO city (id, name, departmentId) VALUES (50226, 'Cumaral', 50);
INSERT INTO city (id, name, departmentId) VALUES (50245, 'El Calvario', 50);
INSERT INTO city (id, name, departmentId) VALUES (50251, 'El Castillo', 50);
INSERT INTO city (id, name, departmentId) VALUES (50270, 'El Dorado', 50);
INSERT INTO city (id, name, departmentId) VALUES (50287, 'Fuente de Oro', 50);
INSERT INTO city (id, name, departmentId) VALUES (50313, 'Granada', 50);
INSERT INTO city (id, name, departmentId) VALUES (50318, 'Guamal', 50);
INSERT INTO city (id, name, departmentId) VALUES (50325, 'Mapiripán', 50);
INSERT INTO city (id, name, departmentId) VALUES (50330, 'Mesetas', 50);
INSERT INTO city (id, name, departmentId) VALUES (50350, 'La Macarena', 50);
INSERT INTO city (id, name, departmentId) VALUES (50370, 'Uribe', 50);
INSERT INTO city (id, name, departmentId) VALUES (50400, 'Lejanías', 50);
INSERT INTO city (id, name, departmentId) VALUES (50450, 'Puerto Concordia', 50);
INSERT INTO city (id, name, departmentId) VALUES (50568, 'Puerto Gaitán', 50);
INSERT INTO city (id, name, departmentId) VALUES (50573, 'Puerto López', 50);
INSERT INTO city (id, name, departmentId) VALUES (50577, 'Puerto Lleras', 50);
INSERT INTO city (id, name, departmentId) VALUES (50590, 'Puerto Rico', 50);
INSERT INTO city (id, name, departmentId) VALUES (50606, 'Restrepo', 50);
INSERT INTO city (id, name, departmentId) VALUES (50680, 'San Carlos de Guaroa', 50);
INSERT INTO city (id, name, departmentId) VALUES (50683, 'San Juan de Arama', 50);
INSERT INTO city (id, name, departmentId) VALUES (50686, 'San Juanito', 50);
INSERT INTO city (id, name, departmentId) VALUES (50689, 'San Martín', 50);
INSERT INTO city (id, name, departmentId) VALUES (50711, 'Vista Hermosa', 50);
INSERT INTO city (id, name, departmentId) VALUES (52001, 'Pasto', 52);
INSERT INTO city (id, name, departmentId) VALUES (52019, 'Albán', 52);
INSERT INTO city (id, name, departmentId) VALUES (52022, 'Aldana', 52);
INSERT INTO city (id, name, departmentId) VALUES (52036, 'Ancuyá', 52);
INSERT INTO city (id, name, departmentId) VALUES (52051, 'Arboleda', 52);
INSERT INTO city (id, name, departmentId) VALUES (52079, 'Barbacoas', 52);
INSERT INTO city (id, name, departmentId) VALUES (52083, 'Belén', 52);
INSERT INTO city (id, name, departmentId) VALUES (52110, 'Buesaco', 52);
INSERT INTO city (id, name, departmentId) VALUES (52203, 'Colón', 52);
INSERT INTO city (id, name, departmentId) VALUES (52207, 'Consaca', 52);
INSERT INTO city (id, name, departmentId) VALUES (52210, 'Contadero', 52);
INSERT INTO city (id, name, departmentId) VALUES (52215, 'Córdoba', 52);
INSERT INTO city (id, name, departmentId) VALUES (52224, 'Cuaspud', 52);
INSERT INTO city (id, name, departmentId) VALUES (52227, 'Cumbal', 52);
INSERT INTO city (id, name, departmentId) VALUES (52233, 'Cumbitara', 52);
INSERT INTO city (id, name, departmentId) VALUES (52240, 'Chachagüí', 52);
INSERT INTO city (id, name, departmentId) VALUES (52250, 'El Charco', 52);
INSERT INTO city (id, name, departmentId) VALUES (52254, 'El Peñol', 52);
INSERT INTO city (id, name, departmentId) VALUES (52256, 'El Rosario', 52);
INSERT INTO city (id, name, departmentId) VALUES (52258, 'El Tablón de Gómez', 52);
INSERT INTO city (id, name, departmentId) VALUES (52260, 'El Tambo', 52);
INSERT INTO city (id, name, departmentId) VALUES (52287, 'Funes', 52);
INSERT INTO city (id, name, departmentId) VALUES (52317, 'Guachucal', 52);
INSERT INTO city (id, name, departmentId) VALUES (52320, 'Guaitarilla', 52);
INSERT INTO city (id, name, departmentId) VALUES (52323, 'Gualmatán', 52);
INSERT INTO city (id, name, departmentId) VALUES (52352, 'Iles', 52);
INSERT INTO city (id, name, departmentId) VALUES (52354, 'Imués', 52);
INSERT INTO city (id, name, departmentId) VALUES (52356, 'Ipiales', 52);
INSERT INTO city (id, name, departmentId) VALUES (52378, 'La Cruz', 52);
INSERT INTO city (id, name, departmentId) VALUES (52381, 'La Florida', 52);
INSERT INTO city (id, name, departmentId) VALUES (52385, 'La Llanada', 52);
INSERT INTO city (id, name, departmentId) VALUES (52390, 'La Tola', 52);
INSERT INTO city (id, name, departmentId) VALUES (52399, 'La Unión', 52);
INSERT INTO city (id, name, departmentId) VALUES (52405, 'Leiva', 52);
INSERT INTO city (id, name, departmentId) VALUES (52411, 'Linares', 52);
INSERT INTO city (id, name, departmentId) VALUES (52418, 'Los Andes', 52);
INSERT INTO city (id, name, departmentId) VALUES (52427, 'Magüí', 52);
INSERT INTO city (id, name, departmentId) VALUES (52435, 'Mallama', 52);
INSERT INTO city (id, name, departmentId) VALUES (52473, 'Mosquera', 52);
INSERT INTO city (id, name, departmentId) VALUES (52480, 'Nariño', 52);
INSERT INTO city (id, name, departmentId) VALUES (52490, 'Olaya Herrera', 52);
INSERT INTO city (id, name, departmentId) VALUES (52506, 'Ospina', 52);
INSERT INTO city (id, name, departmentId) VALUES (52520, 'Francisco Pizarro', 52);
INSERT INTO city (id, name, departmentId) VALUES (52540, 'Policarpa', 52);
INSERT INTO city (id, name, departmentId) VALUES (52560, 'Potosí', 52);
INSERT INTO city (id, name, departmentId) VALUES (52565, 'Providencia', 52);
INSERT INTO city (id, name, departmentId) VALUES (52573, 'Puerres', 52);
INSERT INTO city (id, name, departmentId) VALUES (52585, 'Pupiales', 52);
INSERT INTO city (id, name, departmentId) VALUES (52612, 'Ricaurte', 52);
INSERT INTO city (id, name, departmentId) VALUES (52621, 'Roberto Payán', 52);
INSERT INTO city (id, name, departmentId) VALUES (52678, 'Samaniego', 52);
INSERT INTO city (id, name, departmentId) VALUES (52683, 'Sandoná', 52);
INSERT INTO city (id, name, departmentId) VALUES (52685, 'San Bernardo', 52);
INSERT INTO city (id, name, departmentId) VALUES (52687, 'San Lorenzo', 52);
INSERT INTO city (id, name, departmentId) VALUES (52693, 'San Pablo', 52);
INSERT INTO city (id, name, departmentId) VALUES (52694, 'San Pedro de Cartago', 52);
INSERT INTO city (id, name, departmentId) VALUES (52696, 'Santa Bárbara', 52);
INSERT INTO city (id, name, departmentId) VALUES (52699, 'Santacruz', 52);
INSERT INTO city (id, name, departmentId) VALUES (52720, 'Sapuyes', 52);
INSERT INTO city (id, name, departmentId) VALUES (52786, 'Taminango', 52);
INSERT INTO city (id, name, departmentId) VALUES (52788, 'Tangua', 52);
INSERT INTO city (id, name, departmentId) VALUES (52835, 'San Andrés de Tumaco', 52);
INSERT INTO city (id, name, departmentId) VALUES (52838, 'Túquerres', 52);
INSERT INTO city (id, name, departmentId) VALUES (52885, 'Yacuanquer', 52);
INSERT INTO city (id, name, departmentId) VALUES (54001, 'Cúcuta', 54);
INSERT INTO city (id, name, departmentId) VALUES (54003, 'Abrego', 54);
INSERT INTO city (id, name, departmentId) VALUES (54051, 'Arboledas', 54);
INSERT INTO city (id, name, departmentId) VALUES (54099, 'Bochalema', 54);
INSERT INTO city (id, name, departmentId) VALUES (54109, 'Bucarasica', 54);
INSERT INTO city (id, name, departmentId) VALUES (54125, 'Cácota', 54);
INSERT INTO city (id, name, departmentId) VALUES (54128, 'Cachirá', 54);
INSERT INTO city (id, name, departmentId) VALUES (54172, 'Chinácota', 54);
INSERT INTO city (id, name, departmentId) VALUES (54174, 'Chitagá', 54);
INSERT INTO city (id, name, departmentId) VALUES (54206, 'Convención', 54);
INSERT INTO city (id, name, departmentId) VALUES (54223, 'Cucutilla', 54);
INSERT INTO city (id, name, departmentId) VALUES (54239, 'Durania', 54);
INSERT INTO city (id, name, departmentId) VALUES (54245, 'El Carmen', 54);
INSERT INTO city (id, name, departmentId) VALUES (54250, 'El Tarra', 54);
INSERT INTO city (id, name, departmentId) VALUES (54261, 'El Zulia', 54);
INSERT INTO city (id, name, departmentId) VALUES (54313, 'Gramalote', 54);
INSERT INTO city (id, name, departmentId) VALUES (54344, 'Hacarí', 54);
INSERT INTO city (id, name, departmentId) VALUES (54347, 'Herrán', 54);
INSERT INTO city (id, name, departmentId) VALUES (54377, 'Labateca', 54);
INSERT INTO city (id, name, departmentId) VALUES (54385, 'La Esperanza', 54);
INSERT INTO city (id, name, departmentId) VALUES (54398, 'La Playa', 54);
INSERT INTO city (id, name, departmentId) VALUES (54405, 'Los Patios', 54);
INSERT INTO city (id, name, departmentId) VALUES (54418, 'Lourdes', 54);
INSERT INTO city (id, name, departmentId) VALUES (54480, 'Mutiscua', 54);
INSERT INTO city (id, name, departmentId) VALUES (54498, 'Ocaña', 54);
INSERT INTO city (id, name, departmentId) VALUES (54518, 'Pamplona', 54);
INSERT INTO city (id, name, departmentId) VALUES (54520, 'Pamplonita', 54);
INSERT INTO city (id, name, departmentId) VALUES (54553, 'Puerto Santander', 54);
INSERT INTO city (id, name, departmentId) VALUES (54599, 'Ragonvalia', 54);
INSERT INTO city (id, name, departmentId) VALUES (54660, 'Salazar', 54);
INSERT INTO city (id, name, departmentId) VALUES (54670, 'San Calixto', 54);
INSERT INTO city (id, name, departmentId) VALUES (54673, 'San Cayetano', 54);
INSERT INTO city (id, name, departmentId) VALUES (54680, 'Santiago', 54);
INSERT INTO city (id, name, departmentId) VALUES (54720, 'Sardinata', 54);
INSERT INTO city (id, name, departmentId) VALUES (54743, 'Silos', 54);
INSERT INTO city (id, name, departmentId) VALUES (54800, 'Teorama', 54);
INSERT INTO city (id, name, departmentId) VALUES (54810, 'Tibú', 54);
INSERT INTO city (id, name, departmentId) VALUES (54820, 'Toledo', 54);
INSERT INTO city (id, name, departmentId) VALUES (54871, 'Villa Caro', 54);
INSERT INTO city (id, name, departmentId) VALUES (54874, 'Villa del Rosario', 54);
INSERT INTO city (id, name, departmentId) VALUES (63001, 'Armenia', 63);
INSERT INTO city (id, name, departmentId) VALUES (63111, 'Buenavista', 63);
INSERT INTO city (id, name, departmentId) VALUES (63130, 'Calarcá', 63);
INSERT INTO city (id, name, departmentId) VALUES (63190, 'Circasia', 63);
INSERT INTO city (id, name, departmentId) VALUES (63212, 'Córdoba', 63);
INSERT INTO city (id, name, departmentId) VALUES (63272, 'Filandia', 63);
INSERT INTO city (id, name, departmentId) VALUES (63302, 'Génova', 63);
INSERT INTO city (id, name, departmentId) VALUES (63401, 'La Tebaida', 63);
INSERT INTO city (id, name, departmentId) VALUES (63470, 'Montenegro', 63);
INSERT INTO city (id, name, departmentId) VALUES (63548, 'Pijao', 63);
INSERT INTO city (id, name, departmentId) VALUES (63594, 'Quimbaya', 63);
INSERT INTO city (id, name, departmentId) VALUES (63690, 'Salento', 63);
INSERT INTO city (id, name, departmentId) VALUES (66001, 'Pereira', 66);
INSERT INTO city (id, name, departmentId) VALUES (66045, 'Apía', 66);
INSERT INTO city (id, name, departmentId) VALUES (66075, 'Balboa', 66);
INSERT INTO city (id, name, departmentId) VALUES (66088, 'Belén de Umbría', 66);
INSERT INTO city (id, name, departmentId) VALUES (66170, 'Dosquebradas', 66);
INSERT INTO city (id, name, departmentId) VALUES (66318, 'Guática', 66);
INSERT INTO city (id, name, departmentId) VALUES (66383, 'La Celia', 66);
INSERT INTO city (id, name, departmentId) VALUES (66400, 'La Virginia', 66);
INSERT INTO city (id, name, departmentId) VALUES (66440, 'Marsella', 66);
INSERT INTO city (id, name, departmentId) VALUES (66456, 'Mistrató', 66);
INSERT INTO city (id, name, departmentId) VALUES (66572, 'Pueblo Rico', 66);
INSERT INTO city (id, name, departmentId) VALUES (66594, 'Quinchía', 66);
INSERT INTO city (id, name, departmentId) VALUES (66682, 'Santa Rosa de Cabal', 66);
INSERT INTO city (id, name, departmentId) VALUES (66687, 'Santuario', 66);
INSERT INTO city (id, name, departmentId) VALUES (68001, 'Bucaramanga', 68);
INSERT INTO city (id, name, departmentId) VALUES (68013, 'Aguada', 68);
INSERT INTO city (id, name, departmentId) VALUES (68020, 'Albania', 68);
INSERT INTO city (id, name, departmentId) VALUES (68051, 'Aratoca', 68);
INSERT INTO city (id, name, departmentId) VALUES (68077, 'Barbosa', 68);
INSERT INTO city (id, name, departmentId) VALUES (68079, 'Barichara', 68);
INSERT INTO city (id, name, departmentId) VALUES (68081, 'Barrancabermeja', 68);
INSERT INTO city (id, name, departmentId) VALUES (68092, 'Betulia', 68);
INSERT INTO city (id, name, departmentId) VALUES (68101, 'Bolívar', 68);
INSERT INTO city (id, name, departmentId) VALUES (68121, 'Cabrera', 68);
INSERT INTO city (id, name, departmentId) VALUES (68132, 'California', 68);
INSERT INTO city (id, name, departmentId) VALUES (68147, 'Capitanejo', 68);
INSERT INTO city (id, name, departmentId) VALUES (68152, 'Carcasí', 68);
INSERT INTO city (id, name, departmentId) VALUES (68160, 'Cepitá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68162, 'Cerrito', 68);
INSERT INTO city (id, name, departmentId) VALUES (68167, 'Charalá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68169, 'Charta', 68);
INSERT INTO city (id, name, departmentId) VALUES (68176, 'Chimá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68179, 'Chipatá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68190, 'Cimitarra', 68);
INSERT INTO city (id, name, departmentId) VALUES (68207, 'Concepción', 68);
INSERT INTO city (id, name, departmentId) VALUES (68209, 'Confines', 68);
INSERT INTO city (id, name, departmentId) VALUES (68211, 'Contratación', 68);
INSERT INTO city (id, name, departmentId) VALUES (68217, 'Coromoro', 68);
INSERT INTO city (id, name, departmentId) VALUES (68229, 'Curití', 68);
INSERT INTO city (id, name, departmentId) VALUES (68235, 'El Carmen de Chucurí', 68);
INSERT INTO city (id, name, departmentId) VALUES (68245, 'El Guacamayo', 68);
INSERT INTO city (id, name, departmentId) VALUES (68250, 'El Peñón', 68);
INSERT INTO city (id, name, departmentId) VALUES (68255, 'El Playón', 68);
INSERT INTO city (id, name, departmentId) VALUES (68264, 'Encino', 68);
INSERT INTO city (id, name, departmentId) VALUES (68266, 'Enciso', 68);
INSERT INTO city (id, name, departmentId) VALUES (68271, 'Florián', 68);
INSERT INTO city (id, name, departmentId) VALUES (68276, 'Floridablanca', 68);
INSERT INTO city (id, name, departmentId) VALUES (68296, 'Galán', 68);
INSERT INTO city (id, name, departmentId) VALUES (68298, 'Gambita', 68);
INSERT INTO city (id, name, departmentId) VALUES (68307, 'Girón', 68);
INSERT INTO city (id, name, departmentId) VALUES (68318, 'Guaca', 68);
INSERT INTO city (id, name, departmentId) VALUES (68320, 'Guadalupe', 68);
INSERT INTO city (id, name, departmentId) VALUES (68322, 'Guapotá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68324, 'Guavatá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68327, 'Güepsa', 68);
INSERT INTO city (id, name, departmentId) VALUES (68344, 'Hato', 68);
INSERT INTO city (id, name, departmentId) VALUES (68368, 'Jesús María', 68);
INSERT INTO city (id, name, departmentId) VALUES (68370, 'Jordán', 68);
INSERT INTO city (id, name, departmentId) VALUES (68377, 'La Belleza', 68);
INSERT INTO city (id, name, departmentId) VALUES (68385, 'Landázuri', 68);
INSERT INTO city (id, name, departmentId) VALUES (68397, 'La Paz', 68);
INSERT INTO city (id, name, departmentId) VALUES (68406, 'Lebríja', 68);
INSERT INTO city (id, name, departmentId) VALUES (68418, 'Los Santos', 68);
INSERT INTO city (id, name, departmentId) VALUES (68425, 'Macaravita', 68);
INSERT INTO city (id, name, departmentId) VALUES (68432, 'Málaga', 68);
INSERT INTO city (id, name, departmentId) VALUES (68444, 'Matanza', 68);
INSERT INTO city (id, name, departmentId) VALUES (68464, 'Mogotes', 68);
INSERT INTO city (id, name, departmentId) VALUES (68468, 'Molagavita', 68);
INSERT INTO city (id, name, departmentId) VALUES (68498, 'Ocamonte', 68);
INSERT INTO city (id, name, departmentId) VALUES (68500, 'Oiba', 68);
INSERT INTO city (id, name, departmentId) VALUES (68502, 'Onzaga', 68);
INSERT INTO city (id, name, departmentId) VALUES (68522, 'Palmar', 68);
INSERT INTO city (id, name, departmentId) VALUES (68524, 'Palmas del Socorro', 68);
INSERT INTO city (id, name, departmentId) VALUES (68533, 'Páramo', 68);
INSERT INTO city (id, name, departmentId) VALUES (68547, 'Piedecuesta', 68);
INSERT INTO city (id, name, departmentId) VALUES (68549, 'Pinchote', 68);
INSERT INTO city (id, name, departmentId) VALUES (68572, 'Puente Nacional', 68);
INSERT INTO city (id, name, departmentId) VALUES (68573, 'Puerto Parra', 68);
INSERT INTO city (id, name, departmentId) VALUES (68575, 'Puerto Wilches', 68);
INSERT INTO city (id, name, departmentId) VALUES (68615, 'Rionegro', 68);
INSERT INTO city (id, name, departmentId) VALUES (68655, 'Sabana de Torres', 68);
INSERT INTO city (id, name, departmentId) VALUES (68669, 'San Andrés', 68);
INSERT INTO city (id, name, departmentId) VALUES (68673, 'San Benito', 68);
INSERT INTO city (id, name, departmentId) VALUES (68679, 'San Gil', 68);
INSERT INTO city (id, name, departmentId) VALUES (68682, 'San Joaquín', 68);
INSERT INTO city (id, name, departmentId) VALUES (68684, 'San José de Miranda', 68);
INSERT INTO city (id, name, departmentId) VALUES (68686, 'San Miguel', 68);
INSERT INTO city (id, name, departmentId) VALUES (68689, 'San Vicente de Chucurí', 68);
INSERT INTO city (id, name, departmentId) VALUES (68705, 'Santa Bárbara', 68);
INSERT INTO city (id, name, departmentId) VALUES (68720, 'Santa Helena del Opón', 68);
INSERT INTO city (id, name, departmentId) VALUES (68745, 'Simacota', 68);
INSERT INTO city (id, name, departmentId) VALUES (68755, 'Socorro', 68);
INSERT INTO city (id, name, departmentId) VALUES (68770, 'Suaita', 68);
INSERT INTO city (id, name, departmentId) VALUES (68773, 'Sucre', 68);
INSERT INTO city (id, name, departmentId) VALUES (68780, 'Suratá', 68);
INSERT INTO city (id, name, departmentId) VALUES (68820, 'Tona', 68);
INSERT INTO city (id, name, departmentId) VALUES (68855, 'Valle de San José', 68);
INSERT INTO city (id, name, departmentId) VALUES (68861, 'Vélez', 68);
INSERT INTO city (id, name, departmentId) VALUES (68867, 'Vetas', 68);
INSERT INTO city (id, name, departmentId) VALUES (68872, 'Villanueva', 68);
INSERT INTO city (id, name, departmentId) VALUES (68895, 'Zapatoca', 68);
INSERT INTO city (id, name, departmentId) VALUES (70001, 'Sincelejo', 70);
INSERT INTO city (id, name, departmentId) VALUES (70110, 'Buenavista', 70);
INSERT INTO city (id, name, departmentId) VALUES (70124, 'Caimito', 70);
INSERT INTO city (id, name, departmentId) VALUES (70204, 'Coloso', 70);
INSERT INTO city (id, name, departmentId) VALUES (70215, 'Corozal', 70);
INSERT INTO city (id, name, departmentId) VALUES (70221, 'Coveñas', 70);
INSERT INTO city (id, name, departmentId) VALUES (70230, 'Chalán', 70);
INSERT INTO city (id, name, departmentId) VALUES (70233, 'El Roble', 70);
INSERT INTO city (id, name, departmentId) VALUES (70235, 'Galeras', 70);
INSERT INTO city (id, name, departmentId) VALUES (70265, 'Guaranda', 70);
INSERT INTO city (id, name, departmentId) VALUES (70400, 'La Unión', 70);
INSERT INTO city (id, name, departmentId) VALUES (70418, 'Los Palmitos', 70);
INSERT INTO city (id, name, departmentId) VALUES (70429, 'Majagual', 70);
INSERT INTO city (id, name, departmentId) VALUES (70473, 'Morroa', 70);
INSERT INTO city (id, name, departmentId) VALUES (70508, 'Ovejas', 70);
INSERT INTO city (id, name, departmentId) VALUES (70523, 'Palmito', 70);
INSERT INTO city (id, name, departmentId) VALUES (70670, 'Sampués', 70);
INSERT INTO city (id, name, departmentId) VALUES (70678, 'San Benito Abad', 70);
INSERT INTO city (id, name, departmentId) VALUES (70702, 'San Juan de Betulia', 70);
INSERT INTO city (id, name, departmentId) VALUES (70708, 'San Marcos', 70);
INSERT INTO city (id, name, departmentId) VALUES (70713, 'San Onofre', 70);
INSERT INTO city (id, name, departmentId) VALUES (70717, 'San Pedro', 70);
INSERT INTO city (id, name, departmentId) VALUES (70742, 'San Luis de Sincé', 70);
INSERT INTO city (id, name, departmentId) VALUES (70771, 'Sucre', 70);
INSERT INTO city (id, name, departmentId) VALUES (70820, 'Santiago de Tolú', 70);
INSERT INTO city (id, name, departmentId) VALUES (70823, 'Tolú Viejo', 70);
INSERT INTO city (id, name, departmentId) VALUES (73001, 'Ibagué', 73);
INSERT INTO city (id, name, departmentId) VALUES (73024, 'Alpujarra', 73);
INSERT INTO city (id, name, departmentId) VALUES (73026, 'Alvarado', 73);
INSERT INTO city (id, name, departmentId) VALUES (73030, 'Ambalema', 73);
INSERT INTO city (id, name, departmentId) VALUES (73043, 'Anzoátegui', 73);
INSERT INTO city (id, name, departmentId) VALUES (73055, 'Armero', 73);
INSERT INTO city (id, name, departmentId) VALUES (73067, 'Ataco', 73);
INSERT INTO city (id, name, departmentId) VALUES (73124, 'Cajamarca', 73);
INSERT INTO city (id, name, departmentId) VALUES (73148, 'Carmen de Apicala', 73);
INSERT INTO city (id, name, departmentId) VALUES (73152, 'Casabianca', 73);
INSERT INTO city (id, name, departmentId) VALUES (73168, 'Chaparral', 73);
INSERT INTO city (id, name, departmentId) VALUES (73200, 'Coello', 73);
INSERT INTO city (id, name, departmentId) VALUES (73217, 'Coyaima', 73);
INSERT INTO city (id, name, departmentId) VALUES (73226, 'Cunday', 73);
INSERT INTO city (id, name, departmentId) VALUES (73236, 'Dolores', 73);
INSERT INTO city (id, name, departmentId) VALUES (73268, 'Espinal', 73);
INSERT INTO city (id, name, departmentId) VALUES (73270, 'Falan', 73);
INSERT INTO city (id, name, departmentId) VALUES (73275, 'Flandes', 73);
INSERT INTO city (id, name, departmentId) VALUES (73283, 'Fresno', 73);
INSERT INTO city (id, name, departmentId) VALUES (73319, 'Guamo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73347, 'Herveo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73349, 'Honda', 73);
INSERT INTO city (id, name, departmentId) VALUES (73352, 'Icononzo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73408, 'Lérida', 73);
INSERT INTO city (id, name, departmentId) VALUES (73411, 'Líbano', 73);
INSERT INTO city (id, name, departmentId) VALUES (73443, 'Mariquita', 73);
INSERT INTO city (id, name, departmentId) VALUES (73449, 'Melgar', 73);
INSERT INTO city (id, name, departmentId) VALUES (73461, 'Murillo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73483, 'Natagaima', 73);
INSERT INTO city (id, name, departmentId) VALUES (73504, 'Ortega', 73);
INSERT INTO city (id, name, departmentId) VALUES (73520, 'Palocabildo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73547, 'Piedras', 73);
INSERT INTO city (id, name, departmentId) VALUES (73555, 'Planadas', 73);
INSERT INTO city (id, name, departmentId) VALUES (73563, 'Prado', 73);
INSERT INTO city (id, name, departmentId) VALUES (73585, 'Purificación', 73);
INSERT INTO city (id, name, departmentId) VALUES (73616, 'Rio Blanco', 73);
INSERT INTO city (id, name, departmentId) VALUES (73622, 'Roncesvalles', 73);
INSERT INTO city (id, name, departmentId) VALUES (73624, 'Rovira', 73);
INSERT INTO city (id, name, departmentId) VALUES (73671, 'Saldaña', 73);
INSERT INTO city (id, name, departmentId) VALUES (73675, 'San Antonio', 73);
INSERT INTO city (id, name, departmentId) VALUES (73678, 'San Luis', 73);
INSERT INTO city (id, name, departmentId) VALUES (73686, 'Santa Isabel', 73);
INSERT INTO city (id, name, departmentId) VALUES (73770, 'Suárez', 73);
INSERT INTO city (id, name, departmentId) VALUES (73854, 'Valle de San Juan', 73);
INSERT INTO city (id, name, departmentId) VALUES (73861, 'Venadillo', 73);
INSERT INTO city (id, name, departmentId) VALUES (73870, 'Villahermosa', 73);
INSERT INTO city (id, name, departmentId) VALUES (73873, 'Villarrica', 73);
INSERT INTO city (id, name, departmentId) VALUES (76001, 'Cali', 76);
INSERT INTO city (id, name, departmentId) VALUES (76020, 'Alcalá', 76);
INSERT INTO city (id, name, departmentId) VALUES (76036, 'Andalucía', 76);
INSERT INTO city (id, name, departmentId) VALUES (76041, 'Ansermanuevo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76054, 'Argelia', 76);
INSERT INTO city (id, name, departmentId) VALUES (76100, 'Bolívar', 76);
INSERT INTO city (id, name, departmentId) VALUES (76109, 'Buenaventura', 76);
INSERT INTO city (id, name, departmentId) VALUES (76111, 'Guadalajara de Buga', 76);
INSERT INTO city (id, name, departmentId) VALUES (76113, 'Bugalagrande', 76);
INSERT INTO city (id, name, departmentId) VALUES (76122, 'Caicedonia', 76);
INSERT INTO city (id, name, departmentId) VALUES (76126, 'Calima', 76);
INSERT INTO city (id, name, departmentId) VALUES (76130, 'Candelaria', 76);
INSERT INTO city (id, name, departmentId) VALUES (76147, 'Cartago', 76);
INSERT INTO city (id, name, departmentId) VALUES (76233, 'Dagua', 76);
INSERT INTO city (id, name, departmentId) VALUES (76243, 'El Águila', 76);
INSERT INTO city (id, name, departmentId) VALUES (76246, 'El Cairo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76248, 'El Cerrito', 76);
INSERT INTO city (id, name, departmentId) VALUES (76250, 'El Dovio', 76);
INSERT INTO city (id, name, departmentId) VALUES (76275, 'Florida', 76);
INSERT INTO city (id, name, departmentId) VALUES (76306, 'Ginebra', 76);
INSERT INTO city (id, name, departmentId) VALUES (76318, 'Guacarí', 76);
INSERT INTO city (id, name, departmentId) VALUES (76364, 'Jamundí', 76);
INSERT INTO city (id, name, departmentId) VALUES (76377, 'La Cumbre', 76);
INSERT INTO city (id, name, departmentId) VALUES (76400, 'La Unión', 76);
INSERT INTO city (id, name, departmentId) VALUES (76403, 'La Victoria', 76);
INSERT INTO city (id, name, departmentId) VALUES (76497, 'Obando', 76);
INSERT INTO city (id, name, departmentId) VALUES (76520, 'Palmira', 76);
INSERT INTO city (id, name, departmentId) VALUES (76563, 'Pradera', 76);
INSERT INTO city (id, name, departmentId) VALUES (76606, 'Restrepo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76616, 'Riofrío', 76);
INSERT INTO city (id, name, departmentId) VALUES (76622, 'Roldanillo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76670, 'San Pedro', 76);
INSERT INTO city (id, name, departmentId) VALUES (76736, 'Sevilla', 76);
INSERT INTO city (id, name, departmentId) VALUES (76823, 'Toro', 76);
INSERT INTO city (id, name, departmentId) VALUES (76828, 'Trujillo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76834, 'Tuluá', 76);
INSERT INTO city (id, name, departmentId) VALUES (76845, 'Ulloa', 76);
INSERT INTO city (id, name, departmentId) VALUES (76863, 'Versalles', 76);
INSERT INTO city (id, name, departmentId) VALUES (76869, 'Vijes', 76);
INSERT INTO city (id, name, departmentId) VALUES (76890, 'Yotoco', 76);
INSERT INTO city (id, name, departmentId) VALUES (76892, 'Yumbo', 76);
INSERT INTO city (id, name, departmentId) VALUES (76895, 'Zarzal', 76);
INSERT INTO city (id, name, departmentId) VALUES (81001, 'Arauca', 81);
INSERT INTO city (id, name, departmentId) VALUES (81065, 'Arauquita', 81);
INSERT INTO city (id, name, departmentId) VALUES (81220, 'Cravo Norte', 81);
INSERT INTO city (id, name, departmentId) VALUES (81300, 'Fortul', 81);
INSERT INTO city (id, name, departmentId) VALUES (81591, 'Puerto Rondón', 81);
INSERT INTO city (id, name, departmentId) VALUES (81736, 'Saravena', 81);
INSERT INTO city (id, name, departmentId) VALUES (81794, 'Tame', 81);
INSERT INTO city (id, name, departmentId) VALUES (85001, 'Yopal', 85);
INSERT INTO city (id, name, departmentId) VALUES (85010, 'Aguazul', 85);
INSERT INTO city (id, name, departmentId) VALUES (85015, 'Chámeza', 85);
INSERT INTO city (id, name, departmentId) VALUES (85125, 'Hato Corozal', 85);
INSERT INTO city (id, name, departmentId) VALUES (85136, 'La Salina', 85);
INSERT INTO city (id, name, departmentId) VALUES (85139, 'Maní', 85);
INSERT INTO city (id, name, departmentId) VALUES (85162, 'Monterrey', 85);
INSERT INTO city (id, name, departmentId) VALUES (85225, 'Nunchía', 85);
INSERT INTO city (id, name, departmentId) VALUES (85230, 'Orocué', 85);
INSERT INTO city (id, name, departmentId) VALUES (85250, 'Paz de Ariporo', 85);
INSERT INTO city (id, name, departmentId) VALUES (85263, 'Pore', 85);
INSERT INTO city (id, name, departmentId) VALUES (85279, 'Recetor', 85);
INSERT INTO city (id, name, departmentId) VALUES (85300, 'Sabanalarga', 85);
INSERT INTO city (id, name, departmentId) VALUES (85315, 'Sácama', 85);
INSERT INTO city (id, name, departmentId) VALUES (85325, 'San Luis de Gaceno', 85);
INSERT INTO city (id, name, departmentId) VALUES (85400, 'Támara', 85);
INSERT INTO city (id, name, departmentId) VALUES (85410, 'Tauramena', 85);
INSERT INTO city (id, name, departmentId) VALUES (85430, 'Trinidad', 85);
INSERT INTO city (id, name, departmentId) VALUES (85440, 'Villanueva', 85);
INSERT INTO city (id, name, departmentId) VALUES (86001, 'Mocoa', 86);
INSERT INTO city (id, name, departmentId) VALUES (86219, 'Colón', 86);
INSERT INTO city (id, name, departmentId) VALUES (86320, 'Orito', 86);
INSERT INTO city (id, name, departmentId) VALUES (86568, 'Puerto Asís', 86);
INSERT INTO city (id, name, departmentId) VALUES (86569, 'Puerto Caicedo', 86);
INSERT INTO city (id, name, departmentId) VALUES (86571, 'Puerto Guzmán', 86);
INSERT INTO city (id, name, departmentId) VALUES (86573, 'Leguízamo', 86);
INSERT INTO city (id, name, departmentId) VALUES (86749, 'Sibundoy', 86);
INSERT INTO city (id, name, departmentId) VALUES (86755, 'San Francisco', 86);
INSERT INTO city (id, name, departmentId) VALUES (86757, 'San Miguel', 86);
INSERT INTO city (id, name, departmentId) VALUES (86760, 'Santiago', 86);
INSERT INTO city (id, name, departmentId) VALUES (86865, 'Valle de Guamez', 86);
INSERT INTO city (id, name, departmentId) VALUES (86885, 'Villagarzón', 86);
INSERT INTO city (id, name, departmentId) VALUES (88001, 'San Andrés', 88);
INSERT INTO city (id, name, departmentId) VALUES (88564, 'Providencia', 88);
INSERT INTO city (id, name, departmentId) VALUES (91001, 'Leticia', 91);
INSERT INTO city (id, name, departmentId) VALUES (91263, 'El Encanto', 91);
INSERT INTO city (id, name, departmentId) VALUES (91405, 'La Chorrera', 91);
INSERT INTO city (id, name, departmentId) VALUES (91407, 'La Pedrera', 91);
INSERT INTO city (id, name, departmentId) VALUES (91430, 'La Victoria', 91);
INSERT INTO city (id, name, departmentId) VALUES (91460, 'Miriti Paraná', 91);
INSERT INTO city (id, name, departmentId) VALUES (91530, 'Puerto Alegría', 91);
INSERT INTO city (id, name, departmentId) VALUES (91536, 'Puerto Arica', 91);
INSERT INTO city (id, name, departmentId) VALUES (91540, 'Puerto Nariño', 91);
INSERT INTO city (id, name, departmentId) VALUES (91669, 'Puerto Santander', 91);
INSERT INTO city (id, name, departmentId) VALUES (91798, 'Tarapacá', 91);
INSERT INTO city (id, name, departmentId) VALUES (94001, 'Inírida', 94);
INSERT INTO city (id, name, departmentId) VALUES (94343, 'Barranco Minas', 94);
INSERT INTO city (id, name, departmentId) VALUES (94663, 'Mapiripana', 94);
INSERT INTO city (id, name, departmentId) VALUES (94883, 'San Felipe', 94);
INSERT INTO city (id, name, departmentId) VALUES (94884, 'Puerto Colombia', 94);
INSERT INTO city (id, name, departmentId) VALUES (94885, 'La Guadalupe', 94);
INSERT INTO city (id, name, departmentId) VALUES (94886, 'Cacahual', 94);
INSERT INTO city (id, name, departmentId) VALUES (94887, 'Pana Pana', 94);
INSERT INTO city (id, name, departmentId) VALUES (94888, 'Morichal', 94);
INSERT INTO city (id, name, departmentId) VALUES (95001, 'San José del Guaviare', 95);
INSERT INTO city (id, name, departmentId) VALUES (95015, 'Calamar', 95);
INSERT INTO city (id, name, departmentId) VALUES (95025, 'El Retorno', 95);
INSERT INTO city (id, name, departmentId) VALUES (95200, 'Miraflores', 95);
INSERT INTO city (id, name, departmentId) VALUES (97001, 'Mitú', 97);
INSERT INTO city (id, name, departmentId) VALUES (97161, 'Caruru', 97);
INSERT INTO city (id, name, departmentId) VALUES (97511, 'Pacoa', 97);
INSERT INTO city (id, name, departmentId) VALUES (97666, 'Taraira', 97);
INSERT INTO city (id, name, departmentId) VALUES (97777, 'Papunaua', 97);
INSERT INTO city (id, name, departmentId) VALUES (97889, 'Yavaraté', 97);
INSERT INTO city (id, name, departmentId) VALUES (99001, 'Puerto Carreño', 99);
INSERT INTO city (id, name, departmentId) VALUES (99524, 'La Primavera', 99);
INSERT INTO city (id, name, departmentId) VALUES (99624, 'Santa Rosalía', 99);
INSERT INTO city (id, name, departmentId) VALUES (99773, 'Cumaribo', 99);