INSERT INTO department (id, name) VALUES (5, 'Antioquia');
INSERT INTO department (id, name) VALUES (8, 'Atlántico');
INSERT INTO department (id, name) VALUES (11, 'Bogotá D.C.');
INSERT INTO department (id, name) VALUES (13, 'Bolívar');
INSERT INTO department (id, name) VALUES (15, 'Boyacá');
INSERT INTO department (id, name) VALUES (17, 'Caldas');
INSERT INTO department (id, name) VALUES (18, 'Caquetá');
INSERT INTO department (id, name) VALUES (19, 'Cauca');
INSERT INTO department (id, name) VALUES (20, 'Cesar');
INSERT INTO department (id, name) VALUES (23, 'Córdoba');
INSERT INTO department (id, name) VALUES (25, 'Cundinamarca');
INSERT INTO department (id, name) VALUES (27, 'Chocó');
INSERT INTO department (id, name) VALUES (41, 'Huila');
INSERT INTO department (id, name) VALUES (44, 'La Guajira');
INSERT INTO department (id, name) VALUES (47, 'Magdalena');
INSERT INTO department (id, name) VALUES (50, 'Meta');
INSERT INTO department (id, name) VALUES (52, 'Nariño');
INSERT INTO department (id, name) VALUES (54, 'Norte de Santander');
INSERT INTO department (id, name) VALUES (63, 'Quindío');
INSERT INTO department (id, name) VALUES (66, 'Risaralda');
INSERT INTO department (id, name) VALUES (68, 'Santander');
INSERT INTO department (id, name) VALUES (70, 'Sucre');
INSERT INTO department (id, name) VALUES (73, 'Tolima');
INSERT INTO department (id, name) VALUES (76, 'Valle del Cauca');
INSERT INTO department (id, name) VALUES (81, 'Arauca');
INSERT INTO department (id, name) VALUES (85, 'Casanare');
INSERT INTO department (id, name) VALUES (86, 'Putumayo');
INSERT INTO department (id, name) VALUES (88, 'Archipiélago de San Andrés, Providencia y Santa Catalina');
INSERT INTO department (id, name) VALUES (91, 'Amazonas');
INSERT INTO department (id, name) VALUES (94, 'Guainía');
INSERT INTO department (id, name) VALUES (95, 'Guaviare');
INSERT INTO department (id, name) VALUES (97, 'Vaupés');
INSERT INTO department (id, name) VALUES (99, 'Vichada');